# Generated by Django 3.1.7 on 2021-03-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210319_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='english_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='category',
            name='korean_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
