# Generated by Django 3.1.7 on 2021-03-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_comment_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
