# Generated by Django 3.1.7 on 2021-03-25 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
