# Generated by Django 3.1.7 on 2021-03-26 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210325_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
